# -*- coding: utf-8 -*-
"""summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WqZu3xmy-kGhrAApMCS8T_Evf-B2loyZ
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install newspaper3k
# %pip install lxml_html_clean

from newspaper import Article
from transformers import pipeline

# STEP 1: Input your article URL here
url = "https://edition.cnn.com/politics/live-news/trump-tariffs-cnn-town-hall-04-09-25"  # Example: feel free to change this

# STEP 2: Extract the article
article = Article(url)
article.download()
article.parse()

print("\n TITLE:")
print(article.title)

print("\n ORIGINAL TEXT (Preview):")
print(article.text[:500] + "..." if len(article.text) > 500 else article.text)

# STEP 3: Load Hugging Face summarization pipeline
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# Optional: Limit input text if it’s too long for the model
max_input_tokens = 1024
text = article.text
if len(text.split()) > max_input_tokens:
    text = ' '.join(text.split()[:max_input_tokens])

# STEP 4: Summarize
summary = summarizer(text, max_length=130, min_length=30, do_sample=False)

print("\n SUMMARY:")
print(summary[0]['summary_text'])

